gastro_menu:
    pattern:  /menu
    defaults: { _controller: GastroMenuBundle:Menu:index }

gastro_menu_add_recipe:
    pattern:  /menu/addRecipe/{recipeId}
    defaults: { _controller: GastroMenuBundle:Action:addRecipe }

gastro_menu_remove_recipe:
    pattern:  /menu/removeRecipe/{recipeId}
    defaults: { _controller: GastroMenuBundle:Action:removeRecipe }
