parameters:
#    gastro_menu.example.class: Gastro\MenuBundle\Example

services:
#    gastro_menu.example:
#        class: %gastro_menu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
