gastro_recipe_book:
    pattern:  /recipe-book
    defaults: { _controller: GastroRecipeBookBundle:Default:index }

gastro_recipe_book_show:
    pattern:  /recipe-book/{recipeId}-{recipeName}
    defaults: { _controller: GastroRecipeBookBundle:Default:show }

gastro_recipe_book_add:
    pattern:  /recipe-book/add
    defaults: { _controller: GastroRecipeBookBundle:Default:add }

gastro_recipe_book_edit:
    pattern:  /recipe-book/edit/{recipeId}-{recipeName}
    defaults: { _controller: GastroRecipeBookBundle:Default:edit }

gastro_recipe_book_delete:
    pattern:  /recipe-book/delete/{recipeId}
    defaults: { _controller: GastroRecipeBookBundle:Action:delete }

gastro_recipe_book_add_menu:
    pattern:  /recipe-book/addToMenu/{recipeId}}
    defaults: { _controller: GastroRecipeBookBundle:Action:addToMenu }

gastro_recipe_book_remove_menu:
    pattern:  /recipe-book/removeFromMenu/{recipeId}}
    defaults: { _controller: GastroRecipeBookBundle:Action:removeFromMenu }
