gastro_user_login:
    pattern:  /login
    defaults: { _controller: GastroUserBundle:Security:login }

gastro_user_login_check:
    pattern:  /login_check
    defaults: { _controller: GastroUserBundle:Security:loginCheck }

gastro_user_logout:
    pattern:  /logout
    defaults: { _controller: GastroUserBundle:Security:logout }
