parameters:
#    gastro_user.example.class: Gastro\UserBundle\Example

services:
#    gastro_user.example:
#        class: %gastro_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
