parameters:
#    rocketchef_recipe_book.example.class: RocketChef\RecipeBookBundle\Example

services:
#    rocketchef_recipe_book.example:
#        class: %rocketchef_recipe_book.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
