rocketchef_ingredient:
    pattern:  /ingredient
    defaults: { _controller: RocketChefIngredientBundle:Ingredient:index }
    requirements:
        _method: GET
rocketchef_ingredient_add:
    pattern:  /ingredient/add
    defaults: { _controller: RocketChefIngredientBundle:Ingredient:index }
rocketchef_ingredient_delete:
    pattern:  /ingredient-book/delete/{ingredientId}-{urlRedirect}
    defaults: { _controller: RocketChefIngredientBundle:Action:delete, urlRedirect: null }