parameters:
#    gastro_utils_twig.example.class: Gastro\Utils\TwigBundle\Example

services:
#    gastro_utils_twig.example:
#        class: %gastro_utils_twig.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
