imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id: ~
        name: ROCHEFSESSID
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    use_controller: false
    debug:          "%kernel.debug%"
    bundles:        [ ]
    filters:
        cssrewrite: ~
        less:
            #node: "C:\\Program Files (x86)\\nodejs\\node.exe"
            #node_paths: ["C:\\Users\\Utilisateur\AppData\\Roaming\\npm\\node_modules"]
            node: /usr/local/bin/node
            node_paths: ["/usr/local/lib/node_modules"]
            apply_to: "\.less$"
    assets:
        fontawesome_css:
            inputs:
                - %kernel.root_dir%/../vendor/components/font-awesome/less/font-awesome.less
            filters:
                - less
                - cssrewrite
            output: css/font-awesome.css
        pace_js:
            inputs:
                - %kernel.root_dir%/Resources/js/pace.js/pace.min.js
            output: js/pace.min.js


braincrafted_bootstrap:
    less_filter: less
    assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap
    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.10.2.js

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

