site_site:
    resource: "@SiteSiteBundle/Resources/config/routing.yml"
    prefix:   /
rocketchef_user:
    resource: "@RocketChefUserBundle/Resources/config/routing.yml"
    prefix:   /webapp
rocketchef_menu:
    resource: "@RocketChefMenuBundle/Resources/config/routing.yml"
    prefix:   /webapp
rocketchef_dashboard:
    resource: "@RocketChefDashboardBundle/Resources/config/routing.yml"
    prefix:   /webapp
rocketchef_recipe_book:
    resource: "@RocketChefRecipeBookBundle/Resources/config/routing.yml"
    prefix:   /webapp
rocket_chef_ingredient:
    resource: "@RocketChefIngredientBundle/Resources/config/routing.yml"
    prefix:   /webapp
rocketchef_setting:
    resource: "@RocketChefSettingBundle/Resources/config/routing.yml"
    prefix:   /webapp