site_site:
    resource: "@SiteSiteBundle/Resources/config/routing.yml"
    prefix:   /
gastro_user:
    resource: "@GastroUserBundle/Resources/config/routing.yml"
    prefix:   /
gastro_menu:
    resource: "@GastroMenuBundle/Resources/config/routing.yml"
    prefix:   /webapp
gastro_dashboard:
    resource: "@GastroDashboardBundle/Resources/config/routing.yml"
    prefix:   /webapp
gastro_recipe_book:
    resource: "@GastroRecipeBookBundle/Resources/config/routing.yml"
    prefix:   /webapp
gastro_setting:
    resource: "@GastroSettingBundle/Resources/config/routing.yml"
    prefix:   /webapp