gastro_user:
    resource: "@GastroUserBundle/Resources/config/routing.yml"
    prefix:   /

gastro_dashboard:
    resource: "@GastroDashboardBundle/Resources/config/routing.yml"
    prefix:   /app

gastro_recipe_book:
    resource: "@GastroRecipeBookBundle/Resources/config/routing.yml"
    prefix:   /app


