_index:
    pattern: /
    defaults:  { _controller: GastroUserBundle:Security:login }

gastro_menu:
    resource: "@GastroMenuBundle/Resources/config/routing.yml"
    prefix:   /webapp

gastro_user:
    resource: "@GastroUserBundle/Resources/config/routing.yml"
    prefix:   /

gastro_dashboard:
    resource: "@GastroDashboardBundle/Resources/config/routing.yml"
    prefix:   /webapp

gastro_recipe_book:
    resource: "@GastroRecipeBookBundle/Resources/config/routing.yml"
    prefix:   /webapp

gastro_parameter:
    resource: "@GastroParameterBundle/Resources/config/routing.yml"
    prefix:   /webapp


