security:
    encoders:
        Gastro\UserBundle\Entity\User:
            algorithm:        md5
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        userbundle:
            entity: { class: Gastro\UserBundle\Entity\User, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: userbundle
            form_login:
                login_path: gastro_user_login
                check_path: gastro_user_login_check
                always_use_default_target_path: true
                default_target_path: gastro_dashboard
            logout:
                path:     gastro_user_logout
                target:   gastro_user_login
            anonymous:    true
            security: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/webapp/, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
