rocketchef_selling:
    path:     /selling
    defaults: { _controller: RocketChefSellingBundle:Selling:index }
    requirements:
        _method: GET
rocketchef_selling_ajax:
    path:     /selling/data
    defaults: { _controller: RocketChefSellingBundle:Action:getData }
    requirements:
        _method: GET
rocketchef_selling_add:
    path:     /selling/add
    defaults: { _controller: RocketChefSellingBundle:Selling:add }
