parameters:
#    rocket_chef_selling.example.class: RocketChef\SellingBundle\Example

services:
#    rocket_chef_selling.example:
#        class: %rocket_chef_selling.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
