rocketchef_menu:
    pattern:  /menu
    defaults: { _controller: RocketChefMenuBundle:Menu:index }
    requirements:
        _method: GET
rocketchef_menu_add_recipe:
    pattern:  /menu/addRecipe/{recipeId}
    defaults: { _controller: RocketChefMenuBundle:Action:addRecipe }
rocketchef_menu_remove_recipe:
    pattern:  /menu/removeRecipe/{recipeId}
    defaults: { _controller: RocketChefMenuBundle:Action:removeRecipe }
