parameters:
#    rocketchef_menu.example.class: RocketChef\MenuBundle\Example

services:
#    rocketchef_menu.example:
#        class: %rocketchef_menu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
