rocketchef_user_login:
    pattern:  /login
    defaults: { _controller: RocketChefUserBundle:Security:login }
rocketchef_user_login_check:
    pattern:  /login_check
    defaults: { _controller: RocketChefUserBundle:Security:loginCheck }
rocketchef_user_register:
    pattern:  /register
    defaults: { _controller: RocketChefUserBundle:Security:register }
rocketchef_user_logout:
    pattern:  /logout
    defaults: { _controller: RocketChefUserBundle:Security:logout }
rocketchef_user_change_pass:
    pattern:  /editPass
    defaults: { _controller: RocketChefUserBundle:Security:editPass }